### ISSUE TITLE
sidekiqはインストールしてるけど設定ファイル一式がない

### ISSUE THREAD

**Issue by nashirox** [wmegane/rails_template#14]
@ihatov08 吉田さんしか詳細知らないと思うので、設定ファイルを入れててもらえますか？
あと、ダッシュボードも使えるようにお願いします

**Comment by ihatov08** [comment]
@nashirox sidekiqの設定入れました。確認のため、masterにすでにpushしています。

**Comment by ihatov08** [comment]
該当コミットです
https://github.com/wmegane/rails_template/commit/8bb376e97c3d7344d95408bb391838c84f76d95e
https://github.com/wmegane/rails_template/commit/ec675f6bf85998357296d8e607c22ce4867af13d
